import { write as ptyWrite } from "@/lib/pty";
import { addTicket, ask, cancel, cycleMode, decide, listSessions, resume, rewind, rewindRequest, runBang, saveMemory, showUsage } from "@/store/claude";
import {
  activeId,
  busy,
  chat,
  chats,
  closeResume,
  currentLog,
  git,
  info,
  isProjectChat,
  knownCommands,
  live,
  openResume,
  pendingPermission,
  queue,
  rate,
  rateLoading,
  repo,
  repos,
  resumeScreen,
  runs,
  selectChat,
  settings,
  suggestions,
  tab,
  tabs,
  toast,
  usageOpen,
  type Tab,
} from "@/store/state";
import {
  altScreen,
  altSinks,
  clearShell,
  closeTab,
  drainAlt,
  newTab,
  runCommand,
  selectTab,
  sendInput,
  setTermSize,
  shellRuns,
  tabBusy,
  writeRaw,
  zshComplete,
} from "@/store/terminal";

export { BUILTINS, EFFORTS, fmtTokens, modelLabel, MODELS, MODES, untilde, type Attachment, type Tab } from "@/store/state";
import { statusLines as statusLinesRef } from "@/store/claude";

function interruptTab(t: Tab) {
  if (t.mode === "shell") return ptyWrite(t.id, "\x03");
  if (resumeScreen[t.id]) return closeResume(t);
  const c = chat.value;
  if (c && runs[c.key]) return cancel(c);
  t.mode = "shell";
}

export function useCockpit() {
  return {
    repos,
    chats,
    repo,
    chat,
    currentLog,
    busy,
    live,
    info,
    settings,
    rate,
    rateLoading,
    usageOpen,
    toast,
    isProjectChat,
    selectChat,
    tabs,
    tab,
    activeId,
    newTab,
    closeTab,
    selectTab,
    tabBusy,
    shellRuns,
    altScreen,
    altSinks,
    drainAlt,
    setTermSize,
    sendInput,
    clearShell,
    zshComplete,
    writeRaw,
    runCommand,
    interruptTab,
    resumeScreen,
    openResume,
    closeResume,
    suggestions,
    knownCommands,
    git,
    addTicket,
    showUsage,
    listSessions,
    resume,
    ask,
    cancel,
    runs,
    queue,
    decide,
    pendingPermission,
    runBang,
    saveMemory,
    rewind,
    rewindRequest,
    statusLines: statusLinesRef,
    cycleMode,
  };
}
